### ISSUE TITLE
access git-mirror configure facing error 500

### ISSUE THREAD

**Issue by zhongw** [linniksa/redmine_git_mirror#3]
Hi,
The error 500 displayed when I trying to access git_mirror configure, the error log is :
```
Started GET "/settings/plugin/redmine_git_mirror" for 10.109.0.50 at 2019-02-14 12:36:47 +0800
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_git_mirror"}
  Token Update All (2.8ms)  UPDATE `tokens` SET `tokens`.`updated_on` = '2019-02-14 12:36:47' WHERE `tokens`.`user_id` = 5 AND `tokens`.`value` = '78c28beefd2e1d2ee3639f21e634ac81b81f3c02' AND `tokens`.`action` = 'session' AND (created_on > '2019-02-07 12:36:47.747991') AND (updated_on > '2019-02-14 04:36:47.748685')
   (0.5ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 5 LIMIT 1
  Current user: zhongwei (id=5)
  Setting Load (0.4ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'plugin_redmine_git_mirror' ORDER BY `settings`.`id` DESC LIMIT 1
  Rendering settings/plugin.html.erb within layouts/admin
  Rendered plugins/redmine_git_mirror/app/views/git_mirror/_settings.html.erb (18.7ms)
  Rendered settings/plugin.html.erb within layouts/admin (23.0ms)
Completed 500 Internal Server Error in 40ms (ActiveRecord: 4.6ms)

ActionView::Template::Error (uninitialized constant RedmineGitMirror::Settings
Did you mean?  Setting):
    15:       Allow users to change URL (risky)
    16:     </label>
    17:     <%= hidden_field_tag "settings[url_change_allowed]", 0 %>
    18:     <%= check_box_tag "settings[url_change_allowed]", 1, RedmineGitMirror::Settings.url_change_allowed?,
    19:         :id => 'url_change_allowed'
    20:     %>
    21:   </p>

plugins/redmine_git_mirror/app/views/git_mirror/_settings.html.erb:18:in `_plugins_redmine_git_mirror_app_views_git_mirror__settings_html_erb__970999306419086397_47190957072860'
app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__3892187169558330291_47190963568260'
app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__3892187169558330291_47190963568260'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
the info of my redmine instance is:
```
Environment:
  Redmine version                4.0.1.stable.17835
  Ruby version                   2.5.3-p105 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
  GitMirror                      1.8.3.1
Redmine plugins:
  redmine_checklists             3.1.14
  redmine_git_mirror             0.6.0
  redmine_issue_evm              4.2.1
  redmine_lightbox2              0.5.0
  redmine_tags                   4.0.0
  redmine_work_time              0.4.0
```
please let me know if anything needed.
thanks.

**Comment by zhongw** [comment]
The setting page working fine after apply the latest commits.
but I got the following error when i tried to create a repo:
```
URL uninitialized constant RedmineGitMirror::URL Did you mean? URI
```
the log printed in production log:
```
Started POST "/projects/prod/repositories" for 10.109.0.50 at 2019-02-17 20:25:31 +0800
Processing by RepositoriesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"r/IW+iItAQ6OOhC21+57WRQiK12DYSlETT4S5MzR6YDdENdrUEHuPw04/9zU1Tt3dLAVvwAiYK7Jci9MKg==", "repository_scm"=>"GitMirror", "repository"=>{"is_default"=>"0", "identifier"=>"prod", "url"=>"git@site:project.git"}, "commit"=>"创建", "project_id"=>"prod"}
  Token Update All (2.7ms)  UPDATE `tokens` SET `tokens`.`updated_on` = '2019-02-17 20:25:31' WHERE `tokens`.`user_id` = 5 AND `tokens`.`value` = '34069facc48101cc92d82f2bd5daf0dfecd' AND `tokens`.`action` = 'session' AND (created_on > '2019-02-10 20:25:31.920793') AND (updated_on > '2019-02-17 12:25:31.921591')
   (0.3ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 5 LIMIT 1
  Current user: zhongw (id=5)
  Project Load (0.2ms)  SELECT  `projects`.* FROM `projects` WHERE `projects`.`identifier` = 'prod' LIMIT 1
   (0.3ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 11
   (0.1ms)  BEGIN
  Repository Exists (0.3ms)  SELECT  1 AS one FROM `repositories` WHERE `repositories`.`identifier` = BINARY 'prod' AND `repositories`.`project_id` = 11 LIMIT 1
   (0.2ms)  ROLLBACK
  Rendering repositories/new.html.erb within layouts/base
  Rendered repositories/_form.html.erb (1.8ms)
  Rendered repositories/new.html.erb within layouts/base (2.4ms)
  UserPreference Load (0.3ms)  SELECT  `user_preferences`.* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 5 LIMIT 1
  Rendering inline template
  Rendered inline template (0.5ms)
  Rendered plugins/redmine_tags/app/views/tags/_header_assets.html.erb (0.3ms)
  Project Load (0.5ms)  SELECT `projects`.`id`, `projects`.`name`, `projects`.`identifier`, `projects`.`lft`, `projects`.`rgt` FROM `projects` INNER JOIN `members` ON `projects`.`id` = `members`.`project_id` WHERE `members`.`user_id` = 5 AND `projects`.`status` != 9 AND `projects`.`status` = 1
  Tracker Exists (0.3ms)  SELECT  1 AS one FROM `trackers` INNER JOIN `projects_trackers` ON `trackers`.`id` = `projects_trackers`.`tracker_id` WHERE `projects_trackers`.`project_id` = 11 LIMIT 1
  CACHE Tracker Exists (0.0ms)  SELECT  1 AS one FROM `trackers` INNER JOIN `projects_trackers` ON `trackers`.`id` = `projects_trackers`.`tracker_id` WHERE `projects_trackers`.`project_id` = 11 LIMIT 1
  Version Exists (0.9ms)  SELECT  1 AS one FROM `versions` INNER JOIN `projects` ON `projects`.`id` = `versions`.`project_id` WHERE (projects.id = 11 OR (projects.status <> 9 AND ( versions.sharing = 'system' OR (projects.lft >= 9 AND projects.rgt <= 10 AND versions.sharing = 'tree') OR (projects.lft < 9 AND projects.rgt > 10 AND versions.sharing IN ('hierarchy', 'descendants')) OR (projects.lft > 9 AND projects.rgt < 10 AND versions.sharing = 'hierarchy')))) LIMIT 1
  Repository Load (0.6ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`project_id` = 11 AND `repositories`.`is_default` = TRUE LIMIT 1
Completed 200 OK in 36ms (Views: 17.7ms | ActiveRecord: 7.2ms)

```
the Permitted url schemes is : git@site:project.git

**Comment by linniksa** [comment]
Hello
I make tests on vanilla redmine 4 
```
Ruby: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
Rails: 5.2.2
Redmine: 4.0.1.stable
```
and it does not reproducible, as i can see only ruby version is differs with you setup
Looks like some autoloading problems on you installation, do you have changes in rails/redmine config files?
anyway can you test `test-autoload` branch?

**Comment by zhongw** [comment]
Hi ,
I tested on test-autoload branch, got the same error.

**Comment by linniksa** [comment]
Thx, i push new commit, can you test it?

**Comment by zhongw** [comment]
tested on test-autoload branch, the problem still exists.
```
Started POST "/projects/prod/repositories" for 10.109.0.50 at 2019-02-18 16:40:37 +0800
Processing by RepositoriesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"PVxJtx3IGv6FThkQM/1bli71/hth7cgVKJTZQAsjUtYWREsuJnH3lFel600qjwqffJolXuZOCpaBbcf1wLDnWA==", "repository_scm"=>"GitMirror", "repository"=>{"is_default"=>"0", "identifier"=>"prod", "url"=>"git@git.prod.cn:prod/WMS.git"}, "commit"=>"创建", "project_id"=>"prod"}
  Token Update All (2.5ms)  UPDATE `tokens` SET `tokens`.`updated_on` = '2019-02-18 16:40:37' WHERE `tokens`.`user_id` = 5 AND `tokens`.`value` = '9c570c22b4abc18632b281a9aca3653a8a4c3d86' AND `tokens`.`action` = 'session' AND (created_on > '2019-02-11 16:40:37.549431') AND (updated_on > '2019-02-18 08:40:37.550422')
   (0.5ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 5 LIMIT 1
  Current user: zhongwei (id=5)
  Project Load (0.3ms)  SELECT  `projects`.* FROM `projects` WHERE `projects`.`identifier` = 'prod' LIMIT 1
   (0.3ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 11
   (0.2ms)  BEGIN
  Repository Exists (0.4ms)  SELECT  1 AS one FROM `repositories` WHERE `repositories`.`identifier` = BINARY 'prod' AND `repositories`.`project_id` = 11 LIMIT 1
   (0.2ms)  ROLLBACK
  Rendering repositories/new.html.erb within layouts/base
  Rendered repositories/_form.html.erb (2.0ms)
  Rendered repositories/new.html.erb within layouts/base (2.7ms)
  UserPreference Load (0.3ms)  SELECT  `user_preferences`.* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 5 LIMIT 1
  Rendering inline template
  Rendered inline template (0.5ms)
  Rendered plugins/redmine_tags/app/views/tags/_header_assets.html.erb (0.2ms)
  Project Load (0.4ms)  SELECT `projects`.`id`, `projects`.`name`, `projects`.`identifier`, `projects`.`lft`, `projects`.`rgt` FROM `projects` INNER JOIN `members` ON `projects`.`id` = `members`.`project_id` WHERE `members`.`user_id` = 5 AND `projects`.`status` != 9 AND `projects`.`status` = 1
  Tracker Exists (0.4ms)  SELECT  1 AS one FROM `trackers` INNER JOIN `projects_trackers` ON `trackers`.`id` = `projects_trackers`.`tracker_id` WHERE `projects_trackers`.`project_id` = 11 LIMIT 1
  CACHE Tracker Exists (0.0ms)  SELECT  1 AS one FROM `trackers` INNER JOIN `projects_trackers` ON `trackers`.`id` = `projects_trackers`.`tracker_id` WHERE `projects_trackers`.`project_id` = 11 LIMIT 1
  Version Exists (0.5ms)  SELECT  1 AS one FROM `versions` INNER JOIN `projects` ON `projects`.`id` = `versions`.`project_id` WHERE (projects.id = 11 OR (projects.status <> 9 AND ( versions.sharing = 'system' OR (projects.lft >= 9 AND projects.rgt <= 10 AND versions.sharing = 'tree') OR (projects.lft < 9 AND projects.rgt > 10 AND versions.sharing IN ('hierarchy', 'descendants')) OR (projects.lft > 9 AND projects.rgt < 10 AND versions.sharing = 'hierarchy')))) LIMIT 1
  Repository Load (0.3ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`project_id` = 11 AND `repositories`.`is_default` = TRUE LIMIT 1
Completed 200 OK in 38ms (Views: 17.6ms | ActiveRecord: 6.6ms)
```
![image](https://user-images.githubusercontent.com/3071894/52939178-74dcfd80-339e-11e9-997e-729295b48364.png)

**Comment by zhongw** [comment]
similar issue : http://www.redmine.org/issues/30753

**Comment by linniksa** [comment]
i still think that this bug depend on ruby version, but can you test https://github.com/linniksa/redmine_git_mirror/tree/deps branch

**Comment by zhongw** [comment]
tested on deps branch and got the following error:
```
Started POST "/projects/product/repositories" for 10.x.x.x at 2019-03-01 08:42:33 +0800
Processing by RepositoriesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"PIWK8ZFOklBzvsa3jFZNrkbk7LtVjbjl0siqSSQGZjYm1dBHuQyDJ3EG7nvXY6Obi6i9pkPAke5hcyNRtAQfLA==", "repository_scm"=>"GitMirror", "repository"=>{"is_default"=>"0", "identifieX(`settings`.`updated_on`) FROM `settings`jituan.cn:product/WMS.git"}, "commit"=>"创建", "project_id"=>"product"}
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 5 LIMIT 1
  Current user: zhongwei (id=5)
  Project Load (0.3ms)  SELECT  `projects`.* FROM `projects` WHERE `projects`.`identifier` = 'product' LIMIT 1
   (0.3ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 11
   (0.2ms)  BEGIN
  Repository::GitMirror Exists (0.6ms)  SELECT  1 AS one FROM `repositories` WHERE `repositories`.`type` IN ('Repository::GitMirror') AND `repositories`.`url` IN ('http://git.git.site/product/WMS', 'http://git.git.site/product/WMS.git', 'https://git.git.site/product/WMS', 'https://git.git.site/product/WMS.git', 'ssh://git@git.git.site/product/WMS', 'ssh://git@git.git.site/product/WMS.git', 'git@git.git.site:product/WMS', 'git@git.git.site:product/WMS.git') AND `repositories`.`id` IS NOT NULL LIMIT 1
  Repository Exists (0.3ms)  SELECT  1 AS one FROM `repositories` WHERE `repositories`.`identifier` = BINARY 'product' AND `repositories`.`project_id` = 11 LIMIT 1
  Repository Exists (0.5ms)  SELECT  1 AS one FROM `repositories` WHERE `repositories`.`project_id` = 11 LIMIT 1
  Repository Update All (0.2ms)  UPDATE `repositories` SET is_default = FALSE WHERE (project_id = 11)
  Repository::GitMirror Create (0.3ms)  INSERT INTO `repositories` (`project_id`, `url`, `root_url`, `type`, `identifier`, `is_default`, `created_on`) VALUES (11, 'git@git.git.site:product/WMS.git', '/cjdata/redmine/plugins/redmine_git_mirror/repos/20190301084234274_git.git.site_product_WMS', 'Repository::GitMirror', 'product', TRUE, '2019-03-01 08:42:34')
   (1.7ms)  COMMIT
Completed 500 Internal Server Error in 2112ms (ActiveRecord: 7.4ms)

NoMethodError (undefined method `[]' for nil:NilClass):

plugins/redmine_git_mirror/app/models/repository/git_mirror.rb:152:in `remove_unreachable_commits'
plugins/redmine_git_mirror/app/models/repository/git_mirror.rb:138:in `fetch'
app/controllers/repositories_controller.rb:44:in `create'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by linniksa** [comment]
and now?

**Comment by zhongw** [comment]
I can create the repo by repos branch now. 
thank you very much.
